spring:
  config:
    import: application-secret.yml

  datasource:
    url: jdbc:h2:file:./data/auth_db;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: NEVER
    schema: classpath:schema.sql

  h2:
    console:
      enabled: true
      path: /h2-console

mybatis:
  mapper-locations:
    - /mappers/*.xml

user:
  profile:
    img:
      default: https://firebasestorage.googleapis.com/v0/b/userprofile-34d52.appspot.com/o/user%2Fdefault.png?alt=media&token=4da24567-16f6-4c71-803e-71ec2136383d
